branches:
  only:
    - master
  
language: erlang
otp_release:
   - 18.1
   - 18.2.1

sudo: false

addons:
  apt:
    packages:
      - build-essential
      - dbus
      - python-dbus
      - python-gobject
      - python-pycurl
      - python-gtk2

install:
  - "make"

script:
  #- "make tests"
  - "make test-report"

notifications:
  email:
    on_success: change
    on_failure: always
