branches:
  only:
    - master
  
language: erlang
otp_release:
   - 18.1
   - 18.2.1

python:
  - '3.2'

sudo: false

addons:
  apt:
    packages:
      - build-essential
      - dbus
      - python-dbus
      - python-gobject
      - python-pycurl
      - gir1.2-gtk-3.0

install:
  - "make"

script:
  #- "make tests"
  - "make test-report"

notifications:
  email:
    on_success: change
    on_failure: always
